# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_options_and_more"),
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "استاد", "verbose_name_plural": "اساتید"},
        ),
        migrations.AlterField(
            model_name="professor",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professors",
                to="institutions.institution",
                verbose_name="مؤسسه",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="national_code",
            field=models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="شماره تلفن"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
    ]
