# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_options_and_more"),
        ("semesters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={"verbose_name": "ترم", "verbose_name_plural": "ترم\u200cها"},
        ),
        migrations.AlterField(
            model_name="semester",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="end_date",
            field=models.DateField(verbose_name="تاریخ پایان"),
        ),
        migrations.AlterField(
            model_name="semester",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="institutions.institution",
                verbose_name="مؤسسه",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Only one semester per institution can be active",
                verbose_name="فعال",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="semester",
            name="start_date",
            field=models.DateField(verbose_name="تاریخ شروع"),
        ),
        migrations.AlterField(
            model_name="semester",
            name="title",
            field=models.CharField(
                help_text="Title of the semester, e.g., 'Fall 1403'",
                max_length=255,
                verbose_name="عنوان",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
    ]
