# Generated by Django 5.2.4 on 2025-09-17 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_alter_course_options_alter_course_code_and_more"),
        ("institutions", "0002_alter_institution_options_and_more"),
        ("locations", "0005_building_unique_building_title_per_institution"),
        (
            "professors",
            "0002_alter_professor_options_alter_professor_created_at_and_more",
        ),
        ("semesters", "0002_alter_semester_options_alter_semester_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی شده در"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="شناسه عمومی",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="توکن دسترسی",
                    ),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="بازه تازه\u200cسازی (ثانیه)",
                        verbose_name="بازه تازه\u200cسازی",
                    ),
                ),
                (
                    "layout_theme",
                    models.CharField(
                        choices=[
                            ("default", "پیش\u200cفرض"),
                            ("dark", "تیره"),
                            ("light", "روشن"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="قالب نمایش",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="display_screens",
                        to="institutions.institution",
                        verbose_name="مؤسسه",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه نمایش",
                "verbose_name_plural": "صفحات نمایش",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="DisplayMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی شده در"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                ("content", models.TextField(verbose_name="پیام")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="اولویت")),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                (
                    "display_screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="displays.displayscreen",
                        verbose_name="صفحه نمایش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام نمایش",
                "verbose_name_plural": "پیام\u200cهای نمایش",
                "ordering": ("-priority", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="DisplayFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی شده در"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="برای تفکیک راحت\u200cتر فیلترها در مدیریت.",
                        max_length=255,
                        verbose_name="عنوان اختیاری",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("شنبه", "شنبه"),
                            ("یکشنبه", "یکشنبه"),
                            ("دوشنبه", "دوشنبه"),
                            ("سه\u200cشنبه", "سه\u200cشنبه"),
                            ("چهارشنبه", "چهارشنبه"),
                            ("پنجشنبه", "پنجشنبه"),
                            ("جمعه", "جمعه"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="روز هفته",
                    ),
                ),
                (
                    "week_type",
                    models.CharField(
                        blank=True,
                        choices=[("every", "هرهفته"), ("odd", "فرد"), ("even", "زوج")],
                        max_length=5,
                        null=True,
                        verbose_name="نوع هفته",
                    ),
                ),
                (
                    "date_override",
                    models.DateField(
                        blank=True,
                        help_text="در صورت تعیین، روز و نوع هفته بر اساس این تاریخ محاسبه می\u200cشود.",
                        null=True,
                        verbose_name="تاریخ دلخواه",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتیب نمایش در پلن صفحه.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="در صورت چرخش بین چند فیلتر، مدت نمایش این فیلتر.",
                        verbose_name="مدت نمایش",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="display_filters",
                        to="locations.classroom",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="display_filters",
                        to="courses.course",
                        verbose_name="درس",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="display_filters",
                        to="professors.professor",
                        verbose_name="استاد",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="display_filters",
                        to="semesters.semester",
                        verbose_name="ترم",
                    ),
                ),
                (
                    "display_screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="displays.displayscreen",
                        verbose_name="صفحه نمایش",
                    ),
                ),
            ],
            options={
                "verbose_name": "فیلتر نمایش",
                "verbose_name_plural": "فیلترهای نمایش",
                "ordering": ("position", "id"),
            },
        ),
    ]
