# Generated by Django 5.2.4 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayfilter',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=20, null=True, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='displayfilter',
            name='week_type',
            field=models.CharField(blank=True, choices=[('هرهفته', 'هرهفته'), ('فرد', 'فرد'), ('زوج', 'زوج')], max_length=20, null=True, verbose_name='نوع هفته'),
        ),
    ]
