# Generated by Django 5.2.4 on 2025-09-18 10:40

from django.db import migrations, models


def migrate_filters_to_json(apps, schema_editor):
    DisplayScreen = apps.get_model("displays", "DisplayScreen")
    DisplayFilter = apps.get_model("displays", "DisplayFilter")

    for screen in DisplayScreen.objects.all():
        filter_payload = []
        filters = (
            DisplayFilter.objects.filter(display_screen=screen, is_deleted=False)
            .order_by("position", "id")
        )
        for filter_obj in filters:
            filter_payload.append(
                {
                    "id": str(filter_obj.pk),
                    "title": filter_obj.title or "",
                    "classroom": filter_obj.classroom_id,
                    "professor": filter_obj.professor_id,
                    "course": filter_obj.course_id,
                    "semester": filter_obj.semester_id,
                    "day_of_week": filter_obj.day_of_week,
                    "week_type": filter_obj.week_type,
                    "date_override": filter_obj.date_override.isoformat()
                    if filter_obj.date_override
                    else None,
                    "position": filter_obj.position,
                    "duration_seconds": filter_obj.duration_seconds,
                    "is_active": filter_obj.is_active,
                    "created_at": filter_obj.created_at.isoformat(),
                    "updated_at": filter_obj.updated_at.isoformat(),
                }
            )
        if filter_payload:
            DisplayScreen.objects.filter(pk=screen.pk).update(filters=filter_payload)


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0002_alter_displayfilter_day_of_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="filters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="تعریف فیلترهای صفحه به\u200cصورت ساختار یافته.",
                verbose_name="پیکربندی فیلترها",
            ),
        ),
        migrations.RunPython(migrate_filters_to_json, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="DisplayFilter",
        ),
    ]
