# Generated by Django 5.2.4 on 2025-09-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0003_displayscreen_filters_delete_displayfilter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DisplayMessage",
        ),
    ]
