# Generated by Django 5.2.4 on 2025-09-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0005_remove_displayscreen_filters_and_more"),
        ("locations", "0005_building_unique_building_title_per_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="filter_building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="display_screens",
                to="locations.building",
                verbose_name="ساختمان",
            ),
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="filter_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداقل ظرفیت"
            ),
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="filter_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="زمان پایان"),
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="filter_group_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="کد گروه"
            ),
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="filter_start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="زمان شروع"),
        ),
    ]
