# Generated by Django 5.2.4 on 2025-10-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0006_displayscreen_filter_building_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="filter_use_current_day_of_week",
            field=models.BooleanField(
                default=False,
                help_text="در صورت فعال بودن، روز هفته بر اساس تاریخ فعلی محاسبه می\u200cشود.",
                verbose_name="تشخیص خودکار روز هفته؟",
            ),
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="filter_use_current_week_type",
            field=models.BooleanField(
                default=False,
                help_text="در صورت فعال بودن، نوع هفته (زوج/فرد) بر اساس تاریخ فعلی تعیین می\u200cشود.",
                verbose_name="تشخیص خودکار نوع هفته؟",
            ),
        ),
    ]
