# Generated by Django 5.2.4 on 2025-10-12 09:37

from django.db import migrations, models
from django.db.models import F


def sync_page_pause_from_duration(apps, schema_editor):
    DisplayScreen = apps.get_model("displays", "DisplayScreen")
    DisplayScreen.objects.all().update(
        filter_page_pause_seconds=F("filter_duration_seconds")
    )


def sync_page_pause_reverse(apps, schema_editor):
    DisplayScreen = apps.get_model("displays", "DisplayScreen")
    DisplayScreen.objects.all().update(filter_page_pause_seconds=0)


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0007_displayscreen_filter_use_current_day_of_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="filter_page_pause_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="مقدار مکث بین نمایش صفحات در نمایشگر عمومی.",
                verbose_name="مدت مکث صفحه (ثانیه)",
            ),
        ),
        migrations.RunPython(sync_page_pause_from_duration, sync_page_pause_reverse),
    ]
