# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("institutions", "0002_alter_institution_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربران"},
        ),
        migrations.AlterField(
            model_name="user",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="The institution this user belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="institutions.institution",
                verbose_name="مؤسسه",
            ),
        ),
    ]
