# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_code"),
        ("institutions", "0002_alter_institution_options_and_more"),
        (
            "professors",
            "0002_alter_professor_options_alter_professor_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "درس", "verbose_name_plural": "دروس"},
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10, verbose_name="کد"),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="institutions.institution",
                verbose_name="مؤسسه",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="course",
            name="offer_code",
            field=models.CharField(max_length=20, unique=True, verbose_name="کد ارائه"),
        ),
        migrations.AlterField(
            model_name="course",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="professors.professor",
                verbose_name="استاد",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="course",
            name="unit_count",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="تعداد واحد"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
    ]
