# Generated by Django 5.2.4 on 2025-07-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set(),
        ),
    ]
