# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_options_and_more"),
        ("locations", "0003_classroom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={
                "verbose_name": "ساختمان",
                "verbose_name_plural": "ساختمان\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="classroom",
            options={"verbose_name": "کلاس", "verbose_name_plural": "کلاس\u200cها"},
        ),
        migrations.AlterField(
            model_name="building",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="institutions.institution",
                verbose_name="مؤسسه",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="building",
            name="title",
            field=models.CharField(
                help_text="ساختمان آموزشی شماره یک",
                max_length=255,
                verbose_name="عنوان",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="locations.building",
                verbose_name="ساختمان",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="title",
            field=models.CharField(
                help_text="مثلاً کلاس ۱۰۱ یا آزمایشگاه شبکه",
                max_length=100,
                verbose_name="عنوان",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
    ]
