# Generated by Django 5.2.4 on 2025-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_options_and_more"),
        ("locations", "0004_alter_building_options_alter_classroom_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("institution", "title"),
                name="unique_building_title_per_institution",
            ),
        ),
    ]
