# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"verbose_name": "مؤسسه", "verbose_name_plural": "مؤسسات"},
        ),
        migrations.AlterField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="نامک"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
    ]
