# Generated by Django 5.2.4 on 2025-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="مسیر فایل لوگوی مؤسسه.",
                null=True,
                upload_to="institution_logos/",
                verbose_name="لوگو",
            ),
        ),
    ]
