# Generated by Django 5.2.4 on 2025-08-19 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0003_alter_course_code"),
        ("institutions", "0001_initial"),
        ("locations", "0003_classroom"),
        ("professors", "0001_initial"),
        ("semesters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("شنبه", "شنبه"),
                            ("یکشنبه", "یکشنبه"),
                            ("دوشنبه", "دوشنبه"),
                            ("سه\u200cشنبه", "سه\u200cشنبه"),
                            ("چهارشنبه", "چهارشنبه"),
                            ("پنجشنبه", "پنجشنبه"),
                            ("جمعه", "جمعه"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "week_type",
                    models.CharField(
                        choices=[("every", "هرهفته"), ("odd", "فرد"), ("even", "زوج")],
                        default="every",
                        max_length=5,
                    ),
                ),
                ("group_code", models.CharField(blank=True, max_length=50, null=True)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="locations.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="institutions.institution",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="professors.professor",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="semesters.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Session",
                "verbose_name_plural": "Class Sessions",
            },
        ),
    ]
