# Generated by Django 5.2.4 on 2025-08-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_options_alter_course_code_and_more"),
        ("institutions", "0002_alter_institution_options_and_more"),
        ("locations", "0004_alter_building_options_alter_classroom_options_and_more"),
        (
            "professors",
            "0002_alter_professor_options_alter_professor_created_at_and_more",
        ),
        ("schedules", "0001_initial"),
        ("semesters", "0002_alter_semester_options_alter_semester_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classsession",
            options={"verbose_name": "جلسه کلاس", "verbose_name_plural": "جلسات کلاس"},
        ),
        migrations.AlterField(
            model_name="classsession",
            name="capacity",
            field=models.PositiveIntegerField(default=0, verbose_name="ظرفیت"),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="locations.classroom",
                verbose_name="کلاس",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="courses.course",
                verbose_name="درس",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ایجاد شده در"
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("شنبه", "شنبه"),
                    ("یکشنبه", "یکشنبه"),
                    ("دوشنبه", "دوشنبه"),
                    ("سه\u200cشنبه", "سه\u200cشنبه"),
                    ("چهارشنبه", "چهارشنبه"),
                    ("پنجشنبه", "پنجشنبه"),
                    ("جمعه", "جمعه"),
                ],
                max_length=10,
                verbose_name="روز هفته",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="end_time",
            field=models.TimeField(verbose_name="زمان پایان"),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="group_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="کد گروه"
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="institutions.institution",
                verbose_name="مؤسسه",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="حذف شده"),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="یادداشت"),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="professors.professor",
                verbose_name="استاد",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="semesters.semester",
                verbose_name="ترم",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="start_time",
            field=models.TimeField(verbose_name="زمان شروع"),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروزرسانی شده در"
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="week_type",
            field=models.CharField(
                choices=[("every", "هرهفته"), ("odd", "فرد"), ("even", "زوج")],
                default="every",
                max_length=5,
                verbose_name="نوع هفته",
            ),
        ),
    ]
