# Generated by Django 5.2.4 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_classsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='week_type',
            field=models.CharField(choices=[('هرهفته', 'هرهفته'), ('فرد', 'فرد'), ('زوج', 'زوج')], default='هرهفته', max_length=15, verbose_name='نوع هفته'),
        ),
    ]
