# Generated by Django 5.2.4 on 2025-10-27 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_institution_logo"),
        ("locations", "0005_building_unique_building_title_per_institution"),
        ("schedules", "0003_alter_classsession_week_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakeupClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی شده در"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                ("date", models.DateField(verbose_name="تاریخ برگزاری")),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("end_time", models.TimeField(verbose_name="زمان پایان")),
                (
                    "group_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="کد گروه جایگزین"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeup_sessions",
                        to="schedules.classsession",
                        verbose_name="جلسه مرجع",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeup_class_sessions",
                        to="locations.classroom",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeup_class_sessions",
                        to="institutions.institution",
                        verbose_name="مؤسسه",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه جبرانی",
                "verbose_name_plural": "جلسات جبرانی",
                "ordering": ("date", "start_time"),
            },
        ),
        migrations.CreateModel(
            name="ClassCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی شده در"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                ("date", models.DateField(verbose_name="تاریخ لغو")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="دلیل"),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="schedules.classsession",
                        verbose_name="جلسه کلاس",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_cancellations",
                        to="institutions.institution",
                        verbose_name="مؤسسه",
                    ),
                ),
            ],
            options={
                "verbose_name": "لغو جلسه",
                "verbose_name_plural": "لغو جلسات",
                "ordering": ("-date", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("class_session", "date"),
                        name="unique_active_cancellation_per_session_and_date",
                    )
                ],
            },
        ),
    ]
